apply plugin: 'com.android.application'

android {
    namespace 'com.sonycab.scannerapp'
    compileSdk 33

    defaultConfig {
        applicationId "com.sonycab.scannerapp"
        minSdkVersion 19
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
